# Generated by Django 4.0.3 on 2022-04-21 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220419_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paystack_charge_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_charge_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='ref',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
