# Generated by Django 4.0.3 on 2022-04-22 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='firstname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
