# Generated by Django 4.0.3 on 2022-04-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_payment_firstname_payment_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='lastname',
        ),
    ]
