# Generated by Django 4.0.3 on 2022-04-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_payment_firstname_remove_payment_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
