# Generated by Django 4.0.3 on 2022-04-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
