# Generated by Django 4.0.3 on 2022-04-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_itemimage_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemimage',
            old_name='images',
            new_name='image',
        ),
    ]
