# Generated by Django 4.0.3 on 2022-04-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_image_item_image_1_item_default_item_image_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='default',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_8',
        ),
    ]
