# Generated by Django 4.0.3 on 2022-06-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_items_pack_drugs_rename_item_packdrug_drug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='drugs',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='user',
        ),
        migrations.RemoveField(
            model_name='packdrug',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='packdrug',
            name='user',
        ),
        migrations.DeleteModel(
            name='Drug',
        ),
        migrations.DeleteModel(
            name='Pack',
        ),
        migrations.DeleteModel(
            name='PackDrug',
        ),
    ]
