# Generated by Django 4.0.3 on 2022-06-13 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_pack_billing_address_remove_pack_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='demand',
            field=models.CharField(choices=[('TP', 'Top sellers'), ('CH', 'Cheap'), ('EX', 'Expensive')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
