# Generated by Django 4.0.3 on 2022-06-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_item_demand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='paystack_customer_id',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='stripe_customer_id',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
