# Generated by Django 4.0.3 on 2022-06-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
